name: 'Deploy app'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: 'Deploy to Digital Ocean'
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
